/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funpref.view.dependentView;

import funpref.controller.DependentController;
import funpref.controller.LogController;
import funpref.controller.Utils;
import funpref.model.Beneficiary;
import funpref.model.Dependent;
import funpref.model.combobox.ComboBoxItem;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author robson
 */
public class DependentJInternalFrame extends javax.swing.JInternalFrame {
    
    private static DependentJInternalFrame dependentJInternalFrame;
    private Dependent currentDependent;
    private final DependentController dependentController;
    private final SimpleDateFormat formatDate;

    /**
     * Creates new form DependentJInternalFrame
     * @param currentDependent
     * @param dependentController
     */
    public DependentJInternalFrame(Dependent currentDependent, DependentController dependentController) {
        this.currentDependent = currentDependent;
        this.dependentController = dependentController;
        formatDate = new SimpleDateFormat("dd/MM/yyyy");        
        initComponents();
    }

    public Dependent getCurrentDependent() {
        return currentDependent;
    }

    public void setCurrentDependent(Dependent currentDependent) {
        this.currentDependent = currentDependent;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jComboBox18 = new javax.swing.JComboBox<>();
        jLabel81 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel34.setText("nome:");

        jLabel35.setText("grau de parentesco:");

        jLabel36.setText("sexo:");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "feminino" }));
        jComboBox7.setSelectedIndex(-1);

        jLabel37.setText("data de nascimento:");

        jLabel38.setText("fone:");

        jLabel39.setText("idade:");

        jLabel61.setText("código:");

        jLabel76.setText("cpf:");

        jButton12.setText("Salvar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton11.setText("Fechar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel81.setText("deficiência:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel76)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel37)
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel39)
                                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel38)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel61)
                                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel81)
                                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel39)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(jLabel81))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        save();
//        saveDependentCRUDJInternalFrame();
        dependentController.getFunprefController().getBeneficiaryController().updateDependentsJTable();
        close();

//        updateDependentsJTable( currentBeneficiary );
//        beneficiaryCRUDJInternalFrame.setVisible(true);
//        dependentCRUDJInternalFrame.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        close();
//        beneficiaryCRUDJInternalFrame.setVisible(true);
//        dependentCRUDJInternalFrame.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        close();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JComboBox<Object> jComboBox18;
    private javax.swing.JComboBox<Object> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField38;
    // End of variables declaration//GEN-END:variables

    
    
    public static DependentJInternalFrame getDependentJInternalFrame(Dependent currentDependent, DependentController dependentController) {
        if (dependentJInternalFrame != null) {
            dependentJInternalFrame.setCurrentDependent(currentDependent);
            //dependentJInternalFrame.dispose();
            dependentJInternalFrame.reset();
        }
        else {
            dependentJInternalFrame = new DependentJInternalFrame(currentDependent, dependentController );
        }
        return dependentJInternalFrame;
    }

    public void reset() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void fillFields(Dependent dependent) {
        jTextField38.setText("" + dependent.getId());
        jTextField20.setText(dependent.getName());
        
        if( dependent.getIdKinship() > 0 ) {
            jComboBox6.setSelectedItem( dependentController.getFunprefController().getjComboBoxModelController().getComboBoxItem(dependent.getIdKinship(), "kinship") );
        }
        
        jComboBox7.setSelectedItem( decodeSex( dependent.getSex() ));
        
        if( dependent.getBirthDate() != null ) {
            jFormattedTextField8.setText( formatDate.format( dependent.getBirthDate() ) );
            jTextField22.setText( Utils.decodePeriod( dependent.getAge() ) );        
        }        
        
        jTextField21.setText(dependent.getPhone()); 
        jTextField14.setText(dependent.getCpf());
        
        if( dependent.getIdDeficiency() > 0 ) {
            jComboBox18.setSelectedItem( dependentController.getFunprefController().getjComboBoxModelController().getComboBoxItem(dependent.getIdDeficiency(), "deficiency") );
        }
    }
    
    public void fillJComboBoxes() {                
        jComboBox6.setModel(dependentController.getFunprefController().getjComboBoxModelController().getModel( "kinship" ));
        jComboBox18.setModel(dependentController.getFunprefController().getjComboBoxModelController().getModel( "deficiency" ));
    }    
    
    private String decodeSex(Beneficiary.Sex sex) {
        String sexString = null;
        
        if( sex == Beneficiary.Sex.MALE ) {
            sexString = "masculino";
        }
        
        else if( sex == Beneficiary.Sex.FEMALE ) {
            sexString = "feminino";
        }        
        
        return sexString;
    }    

    public void setEditableFields(boolean editable) {
        jTextField38.setEditable(false);
        jTextField20.setEditable(editable);
        jComboBox6.setEnabled(editable);
        jComboBox7.setEnabled(editable);
        jFormattedTextField8.setEditable(editable);
        jTextField22.setEditable(false);
        jTextField21.setEditable(editable);    
        jTextField14.setEditable(editable);
        jComboBox18.setEnabled(editable);
        jButton12.setVisible(editable);
    }

    private void save() {
        
        Dependent dependent = new Dependent();
        
        if( Integer.parseInt(jTextField38.getText()) > 0 ) { // atualização
            dependent.setId( Integer.parseInt( jTextField38.getText() ) );
        }
        
        else { // criação
            dependent.setIdUserCreate( dependentController.getFunprefController().getUser().getId());
            dependent.setCreateDate(new Date());
        }        
        
        dependent.setName( jTextField20.getText() );
        dependent.setIdKinship( ((ComboBoxItem)jComboBox6.getSelectedItem()).getId() );
        //dependent.degreeOfKinship = encodeDegreeOfKinship( jComboBox6.getSelectedItem().toString() );
        dependent.setSex( encodeSex( jComboBox7.getSelectedItem().toString() ) );
        try {
            dependent.setBirthDate( formatDate.parse( jFormattedTextField8.getText() ) );
        } catch (ParseException ex) {
            Logger.getLogger(DependentJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            LogController.reportException(DependentJInternalFrame.class.getName(), ex);                
        }
        dependent.setAge( Period.between(dependent.getBirthDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                    (new Date()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate()));      
        dependent.setPhone( jTextField21.getText() ); 
        dependent.setCpf( jTextField14.getText() );
        dependent.setIdDeficiency( ((ComboBoxItem)jComboBox18.getSelectedItem()).getId() );
        
        dependent.setIdUserUpdate( dependentController.getFunprefController().getUser().getId());
        dependent.setUpdateDate(new Date());
        
        //currentBeneficiary.getDependents().add(dependent);
        dependentController.add(dependent);         
    }
    
    private Beneficiary.Sex encodeSex(String sexString) {
        Beneficiary.Sex sex;
        
        if( sexString.compareTo("masculino") == 0 ) {
            sex = Beneficiary.Sex.MALE;
        }
        
        else {
            sex = Beneficiary.Sex.FEMALE;
        }   
        
        return sex;
    } 
    
    private void close() {
        dependentController.getFunprefController().getBeneficiaryController().showBeneficiaryJInternalFrame();
        this.setVisible(false);
    }
}
